### ISSUE TITLE
youtube'tan aralıklı canlı yayın yapan hesaplar da eklenebilir. 

### ISSUE THREAD

**Issue by serkancura** [mertskaplan/multitv#4]
cüneyt özdemir vs gibi youtube'tan canlı yayın yapan kanalları da isteğe bağlı eklemeye izin verebilir

**Comment by mertskaplan** [comment]
Uygulama arayüzünde sağda çıkan ayarlar ikonu ile açılan pencereden YouTube kanalları özelleştirilebiliyor.
